name: flt_worker
description: The flt_worker plugin allows you to schedule and execute Dart background tasks, based on the WorkManager and the BackgroundTasks APIs, for Android and iOS 13+ respectively.
version: 0.1.0
homepage: https://github.com/xinthink/flt_worker/
repository: https://github.com/xinthink/flt_worker/

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: "^1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.thinkng.flt_worker
        pluginClass: FltWorkerPlugin
      ios:
        pluginClass: FltWorkerPlugin
